### PR TITLE
feat(backend): Update API endpoint to use phone number for balance ch…

### PR DESCRIPTION
**Pull request by NkwaTambe**
Update API endpoint to use phone number for balance checking

### CODE REVIEW

**Review by AssahBismarkabah — COMMENTED** [review]
hello @NkwaTambe great. try testing the request with a local DB or a yaml config, directly to ensure that the data is fetched.

**Comment by NkwaTambe** [comment]
> hello @NkwaTambe great. try testing the request with a local DB or a yaml config, directly to ensure that the data is fetched.

yes @AssahBismarkabah  , i am on it

**Review by kouamschekina — APPROVED** [review]
Good

**Review by stephane-segning — APPROVED** [review]

**Comment by NkwaTambe** [comment]
> > hello @NkwaTambe great. try testing the request with a local DB or a yaml config, directly to ensure that the data is fetched.
> 
> yes @AssahBismarkabah , i am on it

hello bismark, so i did some configurations in side the application.yaml file to test the checkbalance api endpoint and all is fine now.

**Review by AssahBismarkabah — APPROVED** [review]

**Review by nancymuyeh — APPROVED** [review]

**Pull request merged**
