### PR TITLE
Feature/basic classes for each service 

### PR DESCRIPTION
**Pull request by AssahBismarkabah**
added  service interface  and implementation

### CODE REVIEW

**Review by stephane-segning — APPROVED** [review]
Good work!

**Comment by AssahBismarkabah** [comment]
hello sir @stephane-segning requesting for review on this PR

**Comment by Motouom** [comment]
Hello @stephane-segning  all the commits have been verified i fixed them. waiting for aproval.

**Comment by stephane-segning** [comment]
Thank you @Motouom but you're missing the classes

**Comment by Motouom** [comment]
Hello sir @stephane-segning , please i don't understand what you mean by **_missing the classes_**

**Pull request closed without merging**
