### PR TITLE
Update the OKPage.tsx file.

### PR DESCRIPTION
**Pull request by Ogenbertrand**

### CODE REVIEW

**Comment by Ogenbertrand** [comment]
@stephane-segning 
Please review my PR.
[fix the build error in the main](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/117/commits/b132a7fc487e477041e4964d790aa71f429a4170)

**Review by bryandino673 — APPROVED** [review]

**Review by stephane-segning — CHANGES_REQUESTED** [review]
The ticket's name is `fea/service worker`, but where is it?

**Comment by Ogenbertrand** [comment]
> The ticket's name is `fea/service worker`, but where is it?

Hello sir the fea/service worker branch was merged in the main branch already, after the the merging was done it happened that one test was failing from the main branch which is the "build test". So what i did was i navigated to the main branch and started debugging from there which i ended up fixing the fault and i created a new PR.

**Comment by Ogenbertrand** [comment]
> > The ticket's name is `fea/service worker`, but where is it?
> 
> Hello sir the fea/service worker branch was merged in the main branch already, after the the merging was done it happened that one test was failing from the main branch which is the "build test". So what i did was i navigated to the main branch and started debugging from there which i ended up fixing the fault and i created a new PR.

After creating the new PR from the main branch it happened that my commits weren't verified so what i did is i undo all the commits from the PR closed it and created another PR which is this one

**Comment by Motouom** [comment]
> > > The ticket's name is `fea/service worker`, but where is it?
> > 
> > 
> > Hello sir the fea/service worker branch was merged in the main branch already, after the the merging was done it happened that one test was failing from the main branch which is the "build test". So what i did was i navigated to the main branch and started debugging from there which i ended up fixing the fault and i created a new PR.
> 
> After creating the new PR from the main branch it happened that my commits weren't verified so my work couldn't be merged what i did is i undo all the commits from the PR closed it and created another PR which is this one

@Ogenbertrand  tag  @stephane-segning  when you are writing a comment if not, he won't see it

**Review by Motouom — APPROVED** [review]

**Comment by stephane-segning** [comment]
> > > The ticket's name is `fea/service worker`, but where is it?
> > 
> > 
> > Hello sir the fea/service worker branch was merged in the main branch already, after the the merging was done it happened that one test was failing from the main branch which is the "build test". So what i did was i navigated to the main branch and started debugging from there which i ended up fixing the fault and i created a new PR.
> 
> After creating the new PR from the main branch it happened that my commits weren't verified so my work couldn't be merged what i did is i undo all the commits from the PR closed it and created another PR which is this one

It's a nice story but not interesting. This PR is created under a specific name. But that name does not match the implementation. Try fixing that

**Comment by Ogenbertrand** [comment]
> > > > The ticket's name is `fea/service worker`, but where is it?
> > > 
> > > 
> > > Hello sir the fea/service worker branch was merged in the main branch already, after the the merging was done it happened that one test was failing from the main branch which is the "build test". So what i did was i navigated to the main branch and started debugging from there which i ended up fixing the fault and i created a new PR.
> > 
> > 
> > After creating the new PR from the main branch it happened that my commits weren't verified so my work couldn't be merged what i did is i undo all the commits from the PR closed it and created another PR which is this one
> 
> It's a nice story but not interesting @Ogenbertrand. This PR is created under a specific name. But that name does not match the implementation. Try fixing that

Okay sir @stephane-segning. I just fixed it

**Comment by stephane-segning** [comment]
> > > > > The ticket's name is `fea/service worker`, but where is it?
> > > > 
> > > > 
> > > > Hello sir the fea/service worker branch was merged in the main branch already, after the the merging was done it happened that one test was failing from the main branch which is the "build test". So what i did was i navigated to the main branch and started debugging from there which i ended up fixing the fault and i created a new PR.
> > > 
> > > 
> > > After creating the new PR from the main branch it happened that my commits weren't verified so my work couldn't be merged what i did is i undo all the commits from the PR closed it and created another PR which is this one
> > 
> > 
> > It's a nice story but not interesting @Ogenbertrand. This PR is created under a specific name. But that name does not match the implementation. Try fixing that
> 
> Okay sir @stephane-segning. I just fixed it

Then what are you updating here?

**Comment by Ogenbertrand** [comment]
@stephane-segning 
I Renamed the component OKpage to OKPage to maintain consistency, 
Called the sendMoney() function within the useEffect() hook to trigger the API call when the component mounts,
Modified the component name in the export statement to match the component's name (OKPage).
[Refactor OKPage component and fix API call](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/117/commits/986de62349a616d7513c8a66aa0fb06efbbcf969)

**Review by stephane-segning — APPROVED** [review]

**Pull request merged**
