### PR TITLE
fix the 'docker build ' error

### PR DESCRIPTION
**Pull request by Ogenbertrand**

### CODE REVIEW

**Comment by Ogenbertrand** [comment]
@stephane-segning 
I modified the okpage.tsx the build command works now with no issues 
[fix the 'docker build ' error](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/114/commits/0c5fc527d88e4540d2f78839788323bd07812779)

**Comment by Ogenbertrand** [comment]
@Arielpetit 
@ValantineSuh 
[fix the 'docker build ' error](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/114/commits/0c5fc527d88e4540d2f78839788323bd07812779)

**Review by ValantineSuh — APPROVED** [review]
Nice Work

**Review by bryandino673 — COMMENTED** [review]
Nice

**Review by bryandino673 — APPROVED** [review]

**Review by stephane-segning — APPROVED** [review]

**Comment by Ogenbertrand** [comment]
@stephane-segning 
[modified the okpage file.](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/114/commits/f94e87c6df98d67368998a996798c552a61cca2c)

**Pull request closed without merging**
