### PR TITLE
Fix backend tests that caused the CI/CD pipeline to fail

### PR DESCRIPTION
**Pull request by kouamschekina**
Fixed the tests which were causing the backend pipeline to fail

### CODE REVIEW

**Review by Koufan-De-King — APPROVED** [review]
Good work.
Make the name of the PR more descriptive and that will be all. 
Something like: "fix backend tests that caused the ci/cd pipeline to fail," since you didn't fix only the SendMoneyImplTest.

**Comment by kouamschekina** [comment]
okay thanks

**Review by NkwaTambe — APPROVED** [review]
Awesome work!!

**Review by stephane-segning — APPROVED** [review]
Good!

**Pull request merged**
