### PR TITLE
Feature/81 remove unused steps from ci/cd files

### PR DESCRIPTION
**Pull request by NkwaTambe**

### CODE REVIEW

**Review by stephane-segning — CHANGES_REQUESTED** [review]
Good start @NkwaTambe. Next step, remove also for the other workflow files

**Comment by NkwaTambe** [comment]
sir @stephane-segning  the tickets say just for the backend files sir(build-service.yaml and  build-translator.yaml)

can you be explicit sir please.

**Comment by NkwaTambe** [comment]
Hello sir @stephane-segning  please review new changes

**Review by stephane-segning — APPROVED** [review]
Thank you @NkwaTambe !

**Pull request merged**
